name: Release

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: 1.Check repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 2.Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 3.Install dependencies
        run: npm install

      - name: 4.Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: 5.Release
        run: npm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 6.Clean up npm token
        run: npm config delete //registry.npmjs.org/:_authToken
