name: Release

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set pnpm token
        run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      # - name: 5.Build
      #   run: pnpm build

      - name: Publish  🚀
        run: pnpm publish

      - name: Clean up pnpm token
        run: pnpm config delete //registry.npmjs.org/:_authToken
