name: Release

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: 📂 Check repository  
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
     
      - name: 📦 Setup pnpm  # https://github.com/marketplace/actions/setup-pnpm
        uses: pnpm/action-setup@v4

      - name: 📦 Setup Node.js # https://github.com/actions/setup-node
        uses: actions/setup-node@v4 
        with:
          node-version-file: './package.json'
          cache: 'pnpm'

      - name: 🔑 Set pnpm token 
        run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: 🧪 Run tests
      #   run: pnpm test

      # - name: 🛠️ Build project
      #   run: pnpm build
 
      - name: 🚀 Release 
        run: pnpm release

      - name: 🧹 Clean up pnpm token
        run: pnpm config delete //registry.npmjs.org/:_authToken
